### PR TITLE
2 examples added

### PR DESCRIPTION
**Pull request by ArminJo**
Hello,
I added 2 examples which were very helpful for me tesing and understanding your distance sensor board.

If you want to use GitHub workflow to test compile your library, have a look at my [workflow script](https://github.com/ArminJo/Github-Actions). If you like it, I can build you a fork with this script for testing.

Best regards
Armin

### CODE REVIEW

**Comment by AndyEngland521** [comment]
Hi @ArminJo , these look pretty slick (who doesn't love a plotter for distance).

Can I get you to bump the version number in library.properties up to 1.2.6 so the Arduino IDE takes note of the differences?

Also, I'm very interested in your workflow script. If you wanted to build us a fork I'd love to give it a look!

Thanks for your hard work,
Andy

**Comment by ArminJo** [comment]
Bumping is done.
Armin

**Comment by ArminJo** [comment]
And workflow script is added and running successfully :-).

**Comment by ArminJo** [comment]
Hello @AndyEngland521 
I added a few commits for documentation and for covering more examples for the platforms.
I hope it is OK for you.
It is the first real live test for my build script :-)

Thanks
Armin

**Comment by ArminJo** [comment]
Hi Andy,
is there anything I can do?
Or something missing?

Armin

**Comment by AndyEngland521** [comment]
Hi Armin,
Sorry, things have been quite hectic around here and I was trying to get a minute to show your script to Nate.

**Pull request merged**
